# Generated by Django 3.2.7 on 2021-09-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='MusicLabel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
