# Generated by Django 3.2.7 on 2021-09-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0004_lyrics_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='Language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.language'),
        ),
    ]
