# Generated by Django 3.2.7 on 2021-09-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0005_lyrics_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-ReleaseDate']},
        ),
        migrations.CreateModel(
            name='All_Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.actor')),
                ('MovieDirector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.moviedirector')),
                ('MusicDirector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.musicdirector')),
                ('Producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lyrics.producer')),
                ('Singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.singer')),
            ],
        ),
    ]
