# Generated by Django 3.2.7 on 2021-10-01 10:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0006_auto_20210930_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.DeleteModel(
            name='All_Bio',
        ),
    ]
