# Generated by Django 3.2.7 on 2021-10-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0007_auto_20211001_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AddField(
            model_name='lyrics',
            name='YouTube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.youtube'),
        ),
        migrations.AddField(
            model_name='movie',
            name='YouTube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.youtube'),
        ),
    ]
